SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE*bs.SALES) TOTAL_SALES
FROM BOOK b, BOOK_SALES bs, AUTHOR a
WHERE b.BOOK_ID = bs.BOOK_ID
AND b.AUTHOR_ID = a.AUTHOR_ID
AND bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;